# Generated by Django 4.1 on 2022-09-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulo',
            old_name='año_lanzamiento',
            new_name='ano_lanzamiento',
        ),
    ]
