# Generated by Django 4.1 on 2022-09-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0002_rename_año_lanzamiento_titulo_ano_lanzamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='titulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_movies.titulo'),
        ),
        migrations.AddField(
            model_name='rating',
            name='titulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_movies.titulo'),
        ),
    ]
