# Generated by Django 4.1 on 2022-09-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0003_genero_titulo_rating_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='titulo',
        ),
    ]
