# Generated by Django 4.1 on 2022-09-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0004_remove_genero_titulo_remove_rating_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_movies.genero'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_movies.rating'),
        ),
    ]
