# Generated by Django 4.1 on 2022-09-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0006_mensajes_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='cuerpo',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
