# Generated by Django 4.1 on 2022-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0007_titulo_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
